train_params:
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 100
  save_steps: 500
  gradient_accumulation_steps: 8
